// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS83CPaugJt7d89v8Bfl6AAx5lumROg_I',
    appId: '1:1002852434700:web:57a9116bf0a4b44097bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    authDomain: 'loginwear-44229.firebaseapp.com',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
    measurementId: 'G-C4W752RK5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rMVGKtL7eS3xpfVwndBqYRNNjmEZevQ',
    appId: '1:1002852434700:android:139324422e89428e97bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwICwzjtZeBIW85iWp0n57-d6sUrednJ4',
    appId: '1:1002852434700:ios:18cb0495a1da38a697bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
    androidClientId: '1002852434700-ab6l906i3fvc8eljpmludjgtukb1slhi.apps.googleusercontent.com',
    iosClientId: '1002852434700-iso3m9katkcaphpd6pv095avrfepe3vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxgooglelog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwICwzjtZeBIW85iWp0n57-d6sUrednJ4',
    appId: '1:1002852434700:ios:53aa7e86a8ed669297bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
    androidClientId: '1002852434700-ab6l906i3fvc8eljpmludjgtukb1slhi.apps.googleusercontent.com',
    iosClientId: '1002852434700-2oahjqj58u9g6srju2lfhmcnfjcvfq8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxgooglelog.RunnerTests',
  );
}
